from datetime import datetime
from sqlalchemy import JSON, DateTime, Float, ForeignKey, Integer, String, Text
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.database import Base


class Scan(Base):
    """Represents an uploaded MRI scan with modalities and segmentation status."""
    __tablename__ = "scans"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, index=True)
    patient_id: Mapped[str] = mapped_column(String(64), index=True)
    file_path: Mapped[str] = mapped_column(String(255))
    modality: Mapped[str] = mapped_column(String(32), default="BraTS-Multimodal")
    status: Mapped[str] = mapped_column(String(32), default="pending")  # pending, completed, failed
    
    # Volumetric metrics in cm^3 (Whole Tumor, Tumor Core, Enhancing Tumor)
    wt_volume_cm3: Mapped[float | None] = mapped_column(Float, nullable=True)
    tc_volume_cm3: Mapped[float | None] = mapped_column(Float, nullable=True)
    et_volume_cm3: Mapped[float | None] = mapped_column(Float, nullable=True)
    
    created_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow)

    reports: Mapped[list["Report"]] = relationship("Report", back_populates="scan", cascade="all, delete-orphan")


class Report(Base):
    """Clinical report generated by Gemini based on MRI findings."""
    __tablename__ = "reports"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, index=True)
    scan_id: Mapped[int] = mapped_column(Integer, ForeignKey("scans.id"), index=True)
    findings: Mapped[str] = mapped_column(Text)
    impression: Mapped[str] = mapped_column(Text)
    recommendations: Mapped[str | None] = mapped_column(Text, nullable=True)
    metadata_json: Mapped[dict | None] = mapped_column(JSON, nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow)

    scan: Mapped["Scan"] = relationship("Scan", back_populates="reports")


class ChatMessage(Base):
    """Conversation history for smolagents interaction."""
    __tablename__ = "chat_messages"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, index=True)
    session_id: Mapped[str] = mapped_column(String(64), index=True)
    role: Mapped[str] = mapped_column(String(16))  # user, assistant, system, tool
    content: Mapped[str] = mapped_column(Text)
    created_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow)
